### ISSUE TITLE
Expected Features?

### ISSUE THREAD

**Issue by CalvinAllen** [mgroves/dotnet-couchbase-ef3#1]
I forked this thing.

I want to help.

I don't know where to start.

Where do I start?  What should I do?

**Comment by mgroves** [comment]
This issue has now become the official planning thread. I'm going to start putting some notes in here today, live on Twitch: twitch.tv/matthewdgroves

The end result may be more issues, a contrib doc, a roadmap doc, etc, or all of the above.

**Comment by mgroves** [comment]
Below are the raw notes from Twitch. Thanks to @CalvinAllen 's suggestion, I'm creating GH Project(s) to hold planning information.

public methods in CouchbaseClientWrapper

DeleteDatabaseOnceAsync
DeleteDatabaseAsync
DeleteDatabaseOnce
DeleteDatabase
CreateDatabaseIfNotExistsAsync
CreateDatabaseIfNotExistsOnce
CreateDatabaseIfNotExists
	-maybe should be "Bucket" instead of "Database"
	-or maybe doesn't need to be implemented

CreateContainerIfNotExistsAsync
CreateContainerIfNotExists
	-there aren't 'containers' in couchbase
	-this might be 'collections' in the future

CreateItem
CreateItemAsync
	-already (partially?) implement

ReplaceItem	
ReplaceItemAsync
	-use _bucket.Replace
	-use _bucket.ReplaceAsync

DeleteItem
DeleteItemOnce
DeleteItemAsync
DeleteItemOnceAsync
	-use _bucket.Remove
	-use _bucket.RemoveAsync
	-don't really need "containerId" for couchbase (yet)

ExecuteSqlQuery
ExecuteSqlQueryAsync
	-huge effort on its own
	
	
DocumentEnumerable
DocumentAsyncEnumerable
	-what are these?
	-probably related to SqlQuery stuff
