### ISSUE TITLE
CouchbaseClientWrapper - ReplaceItem* methods

### ISSUE THREAD

**Issue by mgroves** [mgroves/dotnet-couchbase-ef3#5]
These methods should use Couchbase .NET SDK's `_bucket.Remove` and/or `_bucket.RemoveAsync` methods.

ReplaceItem
ReplaceItemAsync
	-use _bucket.Replace
	-use _bucket.ReplaceAsync

**Comment by mgroves** [comment]
Thank you for the PR, @CalvinAllen! Two issues:

1) The code works great, when running in the same context as the initial data creation. However, since none of the Linq/querying code is implemented yet, I can't test it from within a different context. Not a big deal!

2) When your code replaces the document, it also keeps the "id" data inside the document. Take a look at `CreateItemOnceAsync`. There is some code in there to remove the "id" field before saving it to Couchbase. You can copy/paste that code, or it could be refactored to an "id-stripping" function.

**Comment by CalvinAllen** [comment]
@mgroves Added a new commit to the PR to address your second item.

**Comment by mgroves** [comment]
Thank you, @CalvinAllen!
